### ISSUE TITLE
Failed memory allocation with pictures with resolution bigger than 8M

### ISSUE THREAD

**Issue by marquesVF** [diegotavarez/NeuroscienceAndroidApp#1]
The error stack is the following:
`java.lang.OutOfMemoryError: Failed to allocate a 63922192 byte allocation with 16777120 free bytes and 54MB until OOM
                                                       at org.ejml.data.DenseMatrix64F.<init>(DenseMatrix64F.java:123)
                                                       at org.ejml.simple.SimpleMatrix.<init>(SimpleMatrix.java:149)
                                                       at luc.edu.neuroscienceapp.imageprocessing.ImageProcessing.bmpToMatrix(ImageProcessing.java:44)
                                                       at luc.edu.neuroscienceapp.imageprocessing.ImageProcessing.process(ImageProcessing.java:162)
                                                       at luc.edu.neuroscienceapp.imageprocessing.ImageProcessing.process(ImageProcessing.java:157)
                                                       at luc.edu.neuroscienceapp.activities.PatchesActivity.onCreate(PatchesActivity.java:53)
                                                       at android.app.Activity.performCreate(Activity.java:5975)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)`

The `DenseMatrix64F` function is defined as:

```
/**
     * Creates a new Matrix with the specified shape whose elements initially
     * have the value of zero.
     *
     * @param numRows The number of rows in the matrix.
     * @param numCols The number of columns in the matrix.
     */
    public DenseMatrix64F( int numRows  , int numCols ) {
        data = new double[ numRows * numCols ];

        this.numRows = numRows;
        this.numCols = numCols;
    }
```

I think that there're two possible ways to follow:
- Limit the size of an image taken by the camera (this solution would deal with android sdk and I don't know if it's possible)
- Check the image size coming from the camera and, if the size exceed a certain amount, rescale the image to a feasible size (I'm thinking about working on that).

**Comment by marquesVF** [comment]
My first tempt to solve the problem is on commit ea4c8cc60a7d3634df371ef0ae5482f50f268c41. But it is still crashing sometimes.
I think that maybe we'll need a Camera class implementation to deal directly with camera configurations.
